### ISSUE TITLE
[Q] Example query

### ISSUE THREAD

**Issue by sanchomuzax** [boazreicher/sierra-plot#1]
I don't understand how does it work.
Please, share an example SQL query and Panel options/settings for this layout.
I read it, but I couldn't create a working panel.
Thank you!
![image](https://user-images.githubusercontent.com/2911588/159700178-9953e6b0-acf1-4575-8e26-aade2bcf21ae.png)

**Comment by boazreicher** [comment]
I've added this example: https://github.com/boazreicher/sierra-plot/blob/main/examples/dashboards/mortality2.json

This dashboard is self contained (it includes all of the data as a static CSV, inside the dashboard JSON).  The only requirement is to have the [Testdata DB datasource](https://grafana.com/docs/grafana/latest/datasources/testdata/) enabled (and called `TestData DB`)

The panel options are configured to replicate the posted screenshot

**Comment by sanchomuzax** [comment]
Thank you! Unfortunately the example `json` is too large. I tried to import as file or copoy/paste, but it has an error message:

`413 Request Entity Too Large`

**Comment by boazreicher** [comment]
I suspect you are getting `413` when saving the dashboard because the request goes through some proxy that limits the request content size (see [https://github.com/grafana/grafana/issues/3176](https://github.com/grafana/grafana/issues/3176))

If that can't be changed, you can try the following options:

1. Use the [plugin test environment](https://boazreicher.github.io/sierra-plot/getting_started/#plugin-test-environment):  Clone this repo, cd into the `plugin-test-environment` folder, and then simply run `docker-compose up`.  This will build and run a container with Grafana, the Sierra Plot panel, and a number of sample dashboards, including `Demo - Mortality (static content)` which is what you want.  It will be accessible on `http://localhost:3000`
2. Use the [CSV Datasource plugin](https://grafana.com/grafana/plugins/marcusolsson-csv-datasource/) and the sample CSV and dashboard [found here](https://boazreicher.github.io/sierra-plot/getting_started/#mortality-rates)

**Comment by sanchomuzax** [comment]
Thank you for your help!
